# Generated by Django 4.2.19 on 2025-02-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='普通用户', max_length=10)),
                ('token', models.CharField(default='', max_length=255, verbose_name='token')),
                ('phone_number', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('time', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llmserver.userprofile')),
            ],
        ),
    ]
