# Generated by Django 4.2.19 on 2025-02-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmserver', '0002_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='language',
            field=models.CharField(default='', max_length=255),
        ),
    ]
