# Generated by Django 4.2.19 on 2025-02-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmserver', '0003_userrecord_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
