# Generated by Django 4.2.19 on 2025-02-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmserver', '0004_userrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='code_download',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='pdf_download',
            field=models.CharField(default='', max_length=255),
        ),
    ]
