# Generated by Django 4.2.19 on 2025-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmserver', '0005_userrecord_code_download_userrecord_pdf_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecord',
            name='status',
        ),
        migrations.AddField(
            model_name='userrecord',
            name='code_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='pdf_status',
            field=models.IntegerField(default=1),
        ),
    ]
