# Generated by Django 4.2.19 on 2025-02-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmserver', '0006_remove_userrecord_status_userrecord_code_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='introduce_download',
            field=models.CharField(default='', max_length=255),
        ),
    ]
