# Generated by Django 4.2.19 on 2025-02-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmserver', '0007_userrecord_introduce_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='introduce_status',
            field=models.IntegerField(default=1),
        ),
    ]
