# Generated by Django 4.2.20 on 2025-04-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmserver', '0009_alter_userrecord_code_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='register_download',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userrecord',
            name='register_status',
            field=models.IntegerField(default=0),
        ),
    ]
